### PR TITLE
Snapshud VQ3 shift fix

### LINKED ISSUE #180: SnapsHUD in VQ3 is shifted

### PR DESCRIPTION
**Pull request by suburbski**
Fixes #180

### CODE REVIEW

File: src/cgame/cg_timerun_draw.c [hunk 1]
```diff
@@ -700,6 +700,7 @@ Draw velocity snapping zones (core math taken from iodfengine)
 */
 void CG_DrawVelocitySnapping(void) {
 	vec4_t color[3];
+	qboolean AP = (physics.integer == PHYSICS_MODE_AP_NO_OB || physics.integer == PHYSICS_MODE_AP_OB);
```
Comment (boutetnico) [inline src/cgame/cg_timerun_draw.c]: Please remove the `AP` variable, it is only used once so it's not worth imho.
