### PR TITLE
Info panel upper stats font size fix

### LINKED ISSUE #92: Jump speeds info panel general run stats font size issue
speeds > 10k not supported at start / stop / run max / overall max speed

### PR DESCRIPTION
**Pull request by suburbski**
Fixes #92

### CODE REVIEW

File: src/cgame/cg_timerun_draw.c [hunk 1]
```diff
@@ -940,13 +949,8 @@ void CG_DrawInfoPanel(void) {
...
 		}
 
-		// suburb, decrease font size for higher speeds
 		textScale = 0.12f;
-
-		if (cg.timerunJumpSpeeds[i] >= INFO_PANEL_FONT_ADJUST_NEEDED) {
-			textScaleFactor = 0.02f * GetDigits(cg.timerunJumpSpeeds[i]) - 0.08f;
-			textScale      -= textScaleFactor;
-		}
+		textScale = CG_AdjustFontSize(textScale, cg.timerunJumpSpeeds[i], INFO_PANEL_FONT_ADJUST_NEEDED);
```
Comment (boutetnico) [inline src/cgame/cg_timerun_draw.c]: Remove previous line and change to:
```c
textScale = CG_AdjustFontSize(0.12f, cg.timerunJumpSpeeds[i], INFO_PANEL_FONT_ADJUST_NEEDED);
```
